### PR TITLE
Add OpenEBS to the addons

### PR DESCRIPTION
**Pull request by muratkars**
- Added OpenEBS project

**High level description of the project:**
OpenEBS is a cloud-native storage solution built with the goal of providing containerized storage for containers. Using OpenEBS, a developer can seamlessly get persistent storage for stateful applications on Kubernetes with ease.

## Testing

Installed from the folder and validated with stateful workloads.
```
$ kubectl get pods -n openebs
NAME                                                        READY   STATUS    RESTARTS   AGE
cstor-sparse-pool-6eiu-567459d999-nrjgk                     2/2     Running   0          19m
cstor-sparse-pool-hpu2-766c64cb4d-cbqp7                     2/2     Running   0          19m
cstor-sparse-pool-p59s-6cdd95ffbb-zpfdp                     2/2     Running   0          18m
openebs-gentle-fashion-apiserver-5b979b6559-l2lwt           1/1     Running   0          19m
openebs-gentle-fashion-ndm-6nrjd                            1/1     Running   0          19m
openebs-gentle-fashion-ndm-9clmr                            1/1     Running   0          19m
openebs-gentle-fashion-ndm-lrkcb                            1/1     Running   0          19m
openebs-gentle-fashion-provisioner-54d7d6dd59-rt44s         1/1     Running   0          19m
openebs-gentle-fashion-snapshot-operator-7c6bcf488c-n55lj   2/2     Running   0          19m
```
rel: issue number (if applicable)
This PR will close [2340](https://github.com/openebs/openebs/issues/2340)

### CODE REVIEW

**Comment by dghubble** [comment]
Hey Murat, I appreciate the effort and I'm generally positive about what OpenEBS is working on. But maintaining OpenEBS manifests here doesn't seem like the right fit to me.

The Typhoon cluster addons are components that are closely associated with the cluster and need to be configured for Typhoon in some way. They're maintained/updated and actively used on Typhoon test clusters. For example, Ingress controllers integrate in specific ways with the load balancers on different platforms. Prometheus rules and alerts may be tuned to match baseline behaviors on clusters.

* Justification: I'm not sure what OpenEBS bits would be Typhoon-specific, if any (e.g. vs say OpenEBS maintaining manifests that work on clusters meeting general requirements?). 
* Guarantees: With the official addons, an incompatability with Typhoon could arguably be reason to delay a release (e.g. I consider metrics quite important). With OpenEBS, I think admins are opting for it over other storage solutions (e.g. Typhoon supports CSI/volume-plugin interfaces, but doesn't provide hard guarantees around a particular implementor).
* Maintenance - Tracking changing upstreams, upgrading, and validating components is a lot of work and scope. I'd like to keep Typhoon focused on the Kubernetes distribution and less on validating essential addons.

What about OpenEBS maintaing cluster requirements and example Kubernetes manifests alongside OpenEBS documentation/tutorials instead? I haven't yet truly trialed OpenEBS, but if it works well, I'm happy to cross-link to that in a forthcoming storage document?

I recognize this is a troublesome area. Component authors would like to showcase where their systems work well. Distributions benefit from that as well.

**Comment by muratkars** [comment]
Hi Dalton, thanks for quick feedback. Our motivation was a response to community requests. Having a out-of-the-box simple and light persistent storage solution with minimal resource requirement to expand stateful use cases on Typhoon. 
We really like Typhoon and appreciate your work. I'm not an expert of the design yet, although still learning and would like to discuss with you when possible - There are couple of ideas:
1) Providing basic, maybe optional, persistent storage option for out-of-the-box Prometheus
2) Out of the box storage metrics to Prometheus
3) Metering, logging and monitoring integration in the future
4) Enabling ephemeral / local disk use cases with cloud vendors using Typhoon. Higher performance, cheaper and also persistent with use of OpenEBS.
5) OpenEBS' focus is to "keep it simple". Architected in the first place to minimize any system dependencies, in fact it's all in user space. It just works on any Kubernetes distro.

We can always address the above with tutorials and blogs, which i'm happy to take. OpenEBS has deep-integration with almost all 3rd party K8s distros in some way. If it makes more sense instead we can cross-link to documentation and I can create a section under Integration here [OpenEBS Docs](https://docs.openebs.io/docs/next/ibmcloud.html). Thanks again!

**Comment by dghubble** [comment]
Yeah, I think today the best setup would be OpenEBS Kubernetes manifests kept in OpenEBS docs/examples.

Those ideas sound like good use cases for OpenEBS, but for the addons maintained here, its probably best they not have interdependencies on storage specifics or each other. The Prometheus setup here just illustrates a decent metrics scraping setup for Typhoon, and people can take off with that and customize as needed (add persistent volumes, etc) - but its general and still quite valuable without persistence. The distribution is the cluster module itself, wheras the addons are optional manifest examples that have to be maintained in lock-step.

It looks like OpenEBS already maintains general purpose Kubernetes manifests in [Install OpenEBS using kubectl](https://docs.openebs.io/docs/next/installation.html#install-openebs-using-kubectl) though :tada: And this PR mirrors that 0.8 release. I see the [integrations](https://docs.openebs.io/docs/next/ibmcloud.html) walk through use with specific distributions. If OpenEBS were to want a Typhoon tutorial, perhaps link the Typhoon tutorial for the os/platform pairs OpenEBS aims to support.

For OS, you've got Container Linux, Flatcar Linux (likely supported if CL is), and Fedora. For platform you've got AWS, Azure, bare-metal, DigitalOcean, and Google Cloud. For example, here's the Container Linux / AWS tutorial: https://typhoon.psdn.io/cl/aws/

**Comment by dghubble** [comment]
Thanks for the examples! Closing in favor of the plan proposed above ^

**Pull request closed without merging**
