### PR TITLE
Allow users to specify a custom SSH port

### PR DESCRIPTION
**Pull request by dmyerscough**
High level description of the change.

Allow users to specify what port SSH listen on and configure connection idle timeouts for SSH.

## Testing

```bash
$ terraform plan
$ terraform apply
```

### CODE REVIEW

**Comment by dghubble** [comment]
If you need to add dropins and overwrite `sshd_config, you can now use Container Linux Config snippets https://typhoon.psdn.io/advanced/customization/#hosts. If you need to add your personal preferred sshd_config, that's the place. I'd like to retain the default OS `sshd_config`,which already prevents root and password logins and gets handled by Container Linux.

If you need to change SSH port, its probably best to just maintain a fork for yourself. Doesn't feel like the benefits of an obfuscated port warrant a new variable and supporting it across platforms.

**Comment by dmyerscough** [comment]
That's fine, Ill just maintain this in a separate fork. The default SSH config doesn't match the match the CIS Benchmark standards.

> If you need to change SSH port, its probably best to just maintain a fork for yourself. Doesn't feel like the benefits of an obfuscated port warrant a new variable and supporting it across platforms.

The benefits are avoiding constant scanning/brute force attempts since port 22 is constantly being scanned by botnets.

[1] https://www.cisecurity.org/cis-benchmarks/

**Comment by dghubble** [comment]
Thanks. I'd love to see Container Linux give consideration for meeting those requirements by default. And no disagreement that there are benefits to obfuscating.

**Comment by dghubble** [comment]
If your sshd_config came from some sorta official mandate, maybe file on coreos/bugs?

**Comment by dmyerscough** [comment]
I'll look at filing a bug with Container Linux.

**Pull request closed without merging**
