### PR TITLE
corrected typo and grammar in the issue template

### PR DESCRIPTION
**Pull request by kmarquardsen**

### CODE REVIEW

**Comment by dghubble** [comment]
While you're at it, mind changing "Describe what the goal." to "Describe the goal."?

**Comment by kmarquardsen** [comment]
will do, funny I noticed that and then it slipped my mind

**Comment by kmarquardsen** [comment]
@dghubble I'll squash those later

**Comment by dghubble** [comment]
Yes please

**Comment by dghubble** [comment]
Merged as d48f88cfd6b5ec12a50cad119418f87a6d263a54 (to fix typo in commit message)

**Pull request closed without merging**
