### PR TITLE
Feat/customization

### PR DESCRIPTION
**Pull request by vamshisiddarth**
- [x] Updated Subnet config to create in single az.
- [x] Updated eip config for nlb.

### CODE REVIEW

**Comment by bendrucker** [comment]
Hey guys, figured I'd direct you here:

https://typhoon.psdn.io/advanced/customization/

> Typhoon chooses variables to expose with purpose. If you must customize clusters in ways that aren't supported by input variables, fork Typhoon and maintain a repository with customizations.

Typhoon does not accept a broad set of customizations that are common in corporate environments (e.g. an SSH bastion host with otherwise limited internet exposure) but would conflict with Typhoon's goal of being free and minimal. @takescoop has successfully maintained a fork for 2 years now. You're welcome to reference it, we made a conscious decision to keep it open source:

https://github.com/TakeScoop/typhoon

Perhaps this was just opened in the wrong repo and you already have a fork where you meant to open this. I'm just a user but try to contribute wherever possible. I see you guys filing a lot of issues looking for personalized support—that strains if not breaks Typhoon's [social contract](https://typhoon.psdn.io/#social-contract).

**Comment by dghubble** [comment]
Yeah, this looks like a PR that was meant for an internal repo, made here by mistake. Closing.

**Comment by dghubble** [comment]
thanks @bendrucker

**Comment by vamshisiddarth** [comment]
Sorry guys, yes this was for for the internal repo. I didn't realise while creating.

**Pull request closed without merging**
