### PR TITLE
addons: Update from Prometheus v1.8.2 to v2.0.0

### PR DESCRIPTION
**Pull request by dghubble**
* Migration Guide: https://prometheus.io/docs/prometheus/2.0/migration/
* Use the `promtool` (its in the tarball) to convert v1 rules to v2

### CODE REVIEW

**Comment by dghubble** [comment]
Hm, alertmanager doesn't trigger as it did in Prometheus v1.8.2. Prometheus seems to have some difficulty reaching alertmanager.

```
level=error ts=2017-11-08T10:08:52.910573492Z caller=notifier.go:444 component=notifier alertmanager=http://alertmanager:9093/api/v1/alerts count=1 msg="Error sending alert" err="context deadline exceeded"
```

```
kubectl exec -it prometheus-7444d9dccc-rgm2d -n monitoring /bin/sh
wget alertmanager:9093
Connecting to alertmanager:9093 (10.3.94.82:9093)
wget: can't connect to remote host (10.3.94.82): Connection timed out
```

10.3.94.82 is the correct service IP so this isn't a DNS issue. Nothing interesting in alertmanager logs, unclear if it receives the request.

**Comment by dghubble** [comment]
This turned out to be completely a problem with my alertmanager manifests. I haven't yet added alertmanager to Typhoon's addons so its not really a concern here.

Prometheus 2.0 is looking grand!

**Comment by dghubble** [comment]
Rebased and merged as f570af9418522dc5ce7db28762ff69257af0e493.

**Comment by bcg62** [comment]
@dghubble is alertmanager still missing? Noticing `PrometheusErrorSendingAlerts` and the pods trying to query `alertmanager`

**Comment by dghubble** [comment]
Its not "missing" per-se. If you deploy it on your own, it'll be used. If not it won't.

I personally do deploy alertmanager and recommend it. But haven't opted to maintain the manifests here.

**Pull request closed without merging**
